### ISSUE TITLE
Other wallet support

### ISSUE THREAD

**Issue by mandelmonkey** [LN-Zap/zapconnect#2]
It wasn't too clear from the readme but this only works with zap iOS I assume?
for other wallet wanting to use this they need to convert the macaroon into hex string and prepend/append to the certificate
```
-----BEGIN CERTIFICATE-----\n
\n-----END CERTIFICATE-----
```

**Comment by ottosuess** [comment]
right, the macaroon is base64 encoded, and the tls certificate is a base64 encoded DER certificate.
just to save some space in the qr code.
and PEM is basically base64 encoded DER so you'll just have to add the `-----BEGIN CERTIFICATE-----` and some line break in between.

This is how i do it in the zap app: https://github.com/LN-Zap/zap-iOS/blob/bd44972adf85c7f4aa934d66b0f688324f9ab31f/Lightning/Lnd/Pem.swift
